import { v4 as uuidv4 } from 'uuid';
import { createClient } from '@supabase/supabase-js';
import { uploadFileFromUrl } from './s3';
import dotenv from 'dotenv';

dotenv.config();

// Initialize Supabase client
const supabaseUrl = process.env.VITE_SUPABASE_URL;
// For server-side operations, we should use the service role key to bypass RLS
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  throw new Error('Supabase environment variables are missing');
}

// Create a Supabase client with the service role key to bypass RLS policies
const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    persistSession: false, // Don't persist the session in the server environment
    autoRefreshToken: false,
  }
});

/**
 * Store a generated image in S3 and save its metadata in Supabase
 * @param userId User ID
 * @param imageUrl URL of the generated image
 * @param promptText Text prompt used for generation
 * @returns The stored image data
 */
export async function storeGeneratedImage(
  userId: string,
  imageUrl: string,
  promptText: string
): Promise<any> {
  try {
    // Generate a unique ID for the image
    const imageId = uuidv4();
    
    // Upload the image to S3
    const s3Key = `images/${userId}/${imageId}.png`;
    const s3Url = await uploadFileFromUrl(imageUrl, s3Key);
    
    // Store image metadata in Supabase
    const { data, error } = await supabase
      .from('generated_images')
      .insert({
        id: imageId,
        user_id: userId,
        url: s3Url,
        source_url: imageUrl,
        prompt_text: promptText || '',
        created_at: new Date().toISOString(),
      })
      .select()
      .single();
    
    if (error) {
      console.error('Error storing image metadata:', error);
      // Return basic metadata even if database storage fails
      return {
        id: imageId,
        url: s3Url,
        prompt_text: promptText || '',
        created_at: new Date().toISOString(),
      };
    }
    
    return data;
  } catch (error) {
    console.error('Error storing generated image:', error);
    // Return the original URL if storage fails
    return { url: imageUrl };
  }
}

/**
 * Get all images generated by a user
 * @param userId User ID
 * @returns Array of image metadata
 */
export async function getUserImages(userId: string): Promise<any[]> {
  try {
    const { data, error } = await supabase
      .from('generated_images')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });
    
    if (error) {
      console.error('Error fetching user images:', error);
      return [];
    }
    
    return data || [];
  } catch (error) {
    console.error('Error in getUserImages:', error);
    return [];
  }
}
